export const EVENTS = {
    TRACK_ADDED: 'TRACK_ADDED',
    TRACK_SELECTED: 'TRACK_SELECTED',
    TRACK_UPDATED: 'TRACK_UPDATED', // General update
    PATTERN_CLEARED: 'PATTERN_CLEARED',
    PARAM_CHANGED: 'PARAM_CHANGED',
    LFO_CHANGED: 'LFO_CHANGED',
    SAMPLE_LOADED: 'SAMPLE_LOADED',
    VISUALIZER_UPDATE: 'VISUALIZER_UPDATE',
    GROOVE_APPLIED: 'GROOVE_APPLIED', // New
    CHOKE_GROUP_UPDATED: 'CHOKE_GROUP_UPDATED', // New
    GLOBAL_PAN_SHIFTED: 'GLOBAL_PAN_SHIFTED' // New
};